apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eksa-demo.xyz-tls
spec:
  dnsNames:
  - eksa-demo.xyz
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: le-prod
  secretName: eksa-demo.xyz-tls
