apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-prod
spec:
  acme:
    email: admin@eksa-demo.xyz
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-prod-issuer-account-key
    solvers:
    - http01:
        ingress:
          serviceType: ClusterIP
      selector: {}
