apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor.eksa-demo.xyz
  namespace: harbor
spec:
  dnsNames:
  - harbor.eksa-demo.xyz
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: le-prod
  secretName: harbor.eksa-demo.xyz-tls
