---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: harbor-demo
  namespace: harbor
spec:
  hostname: "harbor.eksa-demo.xyz"
  tlsSecret:
    name: harbor.eksa-demo.xyz-tls
  requestPolicy:
    insecure:
      action: Redirect
